import { motion, useReducedMotion } from 'framer-motion';
import { ArrowDownRight, ArrowUpRight, Bot, Box, Braces, Check, Code2, Cpu, Github, Linkedin, Mail, Menu, Server, Sparkles, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { projects } from '../data/portfolio';
import { SITE } from '../constants/site';

const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] } } };
const dna = [
  { name: 'Frontend', icon: Braces, tags: ['React', 'Next.js', 'TypeScript', 'Tailwind'], tone: 'red' },
  { name: 'Backend', icon: Server, tags: ['Node.js', 'Express', 'MongoDB', 'APIs'], tone: 'ink' },
  { name: 'AI systems', icon: Bot, tags: ['LLM APIs', 'Agents', 'RAG', 'Automation'], tone: 'red' },
  { name: 'Cloud', icon: Box, tags: ['Docker', 'Linux', 'Deployments', 'CI/CD'], tone: 'ink' },
];
const services = [['01', 'Full-stack products', 'From considered frontend systems to secure APIs, databases, and production-ready integrations.'], ['02', 'AI integration', 'Useful AI features, automation workflows, and intelligent interfaces grounded in real product needs.'], ['03', 'Digital experiences', 'Fast, expressive websites and web apps with a strong eye for motion, conversion, and accessibility.'], ['04', 'Cloud & launch', 'Reliable deployment, performance tuning, and the technical foundations that let a product scale.']];
function SectionIntro({ eyebrow, title, copy }) { return <motion.div variants={reveal} className="section-intro"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{copy && <p className="intro-copy">{copy}</p>}</motion.div>; }
function MagneticLink({ children, className = '', ...props }) { return <a className={`magnetic ${className}`} {...props}>{children}</a>; }

export default function PremiumPortfolio() {
  const reduceMotion = useReducedMotion(); const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const update = () => setScrolled(window.scrollY > 18); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  const view = { once: true, amount: 0.16 }; const motionProps = reduceMotion ? {} : { initial: 'hidden', whileInView: 'visible', viewport: view };
  return <div className="portfolio-shell">
    <header className={`site-header ${scrolled ? 'is-scrolled' : ''}`}><a className="brand" href="#home" aria-label="Syed Furqan home"><span>SF</span><b>SYED FURQAN</b></a><nav className={menu ? 'nav-open' : ''} aria-label="Main navigation">{['About', 'Experience', 'Skills', 'Projects', 'Contact'].map((label) => <a key={label} href={`#${label.toLowerCase()}`} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#contact" onClick={() => setMenu(false)}>Let’s talk <ArrowUpRight size={15} /></a></nav><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></header>
    <main>
      <section id="home" className="hero"><div className="hero-grid" aria-hidden="true" /><div className="hero-orb orb-one" aria-hidden="true" /><div className="hero-orb orb-two" aria-hidden="true" /><motion.div className="hero-content" initial="hidden" animate="visible" variants={{ visible: { transition: { staggerChildren: 0.1 } } }}><motion.p variants={reveal} className="hero-kicker"><span /> AVAILABLE FOR SELECTED PROJECTS</motion.p><h1 aria-label="Syed Furqan"><motion.span variants={reveal}>SYED</motion.span><motion.span variants={reveal} className="stroke-text">FURQAN</motion.span></h1><motion.div variants={reveal} className="hero-bottom"><p>Full Stack Developer <i /> AI Engineer <i /> Cloud &amp; System Builder</p><p className="hero-statement">Building intelligent digital experiences with modern technology.</p></motion.div><motion.div variants={reveal} className="hero-actions"><MagneticLink href="#projects" className="button button-primary">Explore selected work <ArrowDownRight size={18} /></MagneticLink><MagneticLink href="#contact" className="text-action">Let’s work together <span>↗</span></MagneticLink></motion.div></motion.div><div className="code-universe" aria-hidden="true"><motion.div className="terminal-card" animate={reduceMotion ? {} : { y: [0, -10, 0] }} transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}><div className="terminal-dots"><i /><i /><i /></div><code><em>const</em> builder = &#123;<br />&nbsp;&nbsp;idea: <b>"useful"</b>,<br />&nbsp;&nbsp;craft: <b>"intentional"</b><br />&#125;</code></motion.div><motion.div className="ai-orb" animate={reduceMotion ? {} : { rotate: 360 }} transition={{ duration: 20, repeat: Infinity, ease: 'linear' }}><span><Sparkles size={22} /></span></motion.div><div className="floating-chip chip-one">AI / 01</div><div className="floating-chip chip-two">SHIP FAST</div></div><a className="scroll-cue" href="#about"><span /> Scroll to explore</a></section>
      <section id="about" className="about section"><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.12 } } }} className="wrap about-grid"><SectionIntro eyebrow="01 — A considered approach" title={<>I don’t just write code.<br /><em>I build momentum.</em></>} /><motion.div variants={reveal} className="about-copy"><p>I design systems, experiences, and products that are clear to use and engineered to last. Every decision lives at the intersection of product intent, technical craft, and human experience.</p><p>My work spans scalable web applications, AI-powered workflows, and modern digital platforms built to feel as good as they perform.</p><div className="about-signature"><span>SF</span><p>Product-minded engineering<br />from Karachi, Pakistan.</p></div></motion.div></motion.div></section>
      <section id="experience" className="experience section pale-section"><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.1 } } }} className="wrap"><SectionIntro eyebrow="02 — The path so far" title={<>Built through <em>real work.</em></>} copy="A practical journey through products, platforms, and the systems behind them." /><div className="timeline">{[['NOW', 'Independent developer & builder', 'Creating complete digital products for ambitious brands, from early concepts to live systems.'], ['WEB', 'Full-stack applications', 'Shipping API-driven products with resilient architecture, responsive interfaces, and clean deployment paths.'], ['LEARN', 'Always compounding', 'Exploring AI systems, modern cloud practices, and the details that make software feel effortless.']].map(([year, title, text]) => <motion.article variants={reveal} className="timeline-item" key={year}><span className="time-label">{year}</span><span className="timeline-dot" /><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight size={19} /></motion.article>)}</div></motion.div></section>
      <section id="skills" className="skills section"><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.1 } } }} className="wrap"><SectionIntro eyebrow="03 — Developer DNA" title={<>A connected <em>system</em> of skills.</>} copy="The strongest work happens when every layer talks to the next." /><div className="dna-map"><div className="dna-center"><Cpu size={30}/><span>BUILD</span></div>{dna.map((group, index) => { const Icon = group.icon; return <motion.article variants={reveal} className={`dna-node node-${index + 1} ${group.tone}`} key={group.name}><Icon size={21}/><h3>{group.name}</h3><div>{group.tags.map(tag => <span key={tag}>{tag}</span>)}</div></motion.article>; })}<svg className="dna-lines" viewBox="0 0 1000 570" preserveAspectRatio="none" aria-hidden="true"><path d="M500 285 L175 140 M500 285 L825 140 M500 285 L175 435 M500 285 L825 435" /></svg></div></motion.div></section>
      <section id="projects" className="projects section pale-section"><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.1 } } }} className="wrap"><SectionIntro eyebrow="04 — Selected work" title={<>Projects made to <em>move</em> business.</>} /><div className="project-list">{projects.slice(0, 4).map((project, index) => <motion.article variants={reveal} className="project-case" key={project.title}><div className="case-index">0{index + 1}</div><div className="case-image"><img src={project.thumbnail} alt={`${project.title} project`} loading="lazy" /><div className="case-hover"><a href={project.url} target="_blank" rel="noreferrer">View case <ArrowUpRight size={18}/></a></div></div><div className="case-copy"><p className="eyebrow">{project.category}</p><h3>{project.title}</h3><p>{project.summary}</p><div className="case-tags">{project.stack.map(tag => <span key={tag}>{tag}</span>)}</div></div></motion.article>)}</div><MagneticLink className="button button-outline all-work" href="#contact">Have a project in mind? <ArrowUpRight size={18}/></MagneticLink></motion.div></section>
      <section className="ai-showcase section"><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.12 } } }} className="wrap ai-layout"><SectionIntro eyebrow="05 — AI playground" title={<>Intelligence, made <em>useful.</em></>} copy="AI isn’t a decorative feature. It is a considered layer for finding, deciding, creating, and automating." /><motion.div variants={reveal} className="ai-panel"><div className="ai-panel-head"><span className="live-dot" /> LIVE WORKFLOW <span>v1.0</span></div><div className="ai-flow"><div><Bot /> <b>Understand</b><small>intent & context</small></div><span>→</span><div><Code2 /> <b>Orchestrate</b><small>tools & actions</small></div><span>→</span><div><Check /> <b>Deliver</b><small>useful output</small></div></div><p>From AI assistants and RAG-powered knowledge to process automation — I turn emerging capabilities into interfaces people can actually use.</p></motion.div></motion.div></section>
      <section className="services section pale-section"><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.08 } } }} className="wrap"><SectionIntro eyebrow="06 — Capabilities" title={<>How I can <em>help.</em></>} /><div className="service-list">{services.map(([number, name, text]) => <motion.article variants={reveal} key={number}><span>{number}</span><h3>{name}</h3><p>{text}</p><ArrowUpRight size={20}/></motion.article>)}</div></motion.div></section>
      <section className="testimonial section"><div className="wrap quote-wrap"><p className="eyebrow">07 — A working philosophy</p><blockquote>“Good software feels <em>inevitable</em> — clear enough to trust, expressive enough to remember.”</blockquote><div><span>SYED FURQAN</span><span>DEVELOPER &amp; PRODUCT BUILDER</span></div></div></section>
      <section id="contact" className="contact section"><div className="contact-glow" /><motion.div {...motionProps} variants={{ visible: { transition: { staggerChildren: 0.12 } } }} className="wrap contact-inner"><motion.p variants={reveal} className="eyebrow">08 — Start a conversation</motion.p><motion.h2 variants={reveal}>Have an idea?<br /><em>Let’s build it.</em></motion.h2><motion.p variants={reveal}>Tell me what you’re working on. I’ll bring product thinking, technical clarity, and a serious eye for the experience.</motion.p><motion.div variants={reveal} className="contact-actions"><MagneticLink href={`mailto:${SITE.email}`} className="button button-primary">Write an email <Mail size={18}/></MagneticLink><a href={SITE.socials.github} target="_blank" rel="noreferrer"><Github size={19}/> GitHub</a><a href={SITE.socials.linkedin} target="_blank" rel="noreferrer"><Linkedin size={19}/> LinkedIn</a></motion.div></motion.div></section>
    </main><footer><div className="wrap"><span>© {new Date().getFullYear()} SYED FURQAN</span><span>Designed &amp; engineered with intent.</span><a href="#home">Back to top ↑</a></div></footer>
  </div>;
}
